export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const LOGIN = 'LOGIN';
export const UPDATE_INFOR = 'UPDATE_INFOR';

export const SHOWLOADING = 'SHOWLOADING';
export const HIDELOADING = 'HIDELOADING';

export const PUSHNOTI = 'PUSHNOTI';
export const HIDENOTI = 'HIDENOTI';

export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';

export const INCREASE_ITEM_CART = 'INCREASE_ITEM_CART';
export const DECREASE_ITEM_CART = 'DECREASE_ITEM_CART';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART';
export const HEART_RESTAURANT = 'HEART_RESTAURANT';
export const PAY_TO_ORDER = 'PAY_TO_ORDER';
export const REST_CART = 'REST_CART';




export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_SUCCESSED = 'UPDATE_NOTIFICATION_SUCCESSED';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIeFICATION_FAIL';

export const UPDATE_REPORT_SUCCESSED = 'UPDATE_REPORT_SUCCESSED';

export const UPDATE_REPORT = 'UPDATE_REPORT';
export const SAVENAVIGATE = 'SAVENAVIGATE';

export const NEW_SCREEN = 'NEW_SCREEN';
export const CLEAR_SCREEN = 'CLEAR_SCREEN';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
